name: KoInsight
url: "https://github.com/GeorgeSG/KoInsight"
image: "ghcr.io/georgesg/koinsight"
version: v0.2.2
slug: koinsight
init: false
description: "Home Assistant Addon for GeorgeSG/KoInsight"
arch: ["aarch64"]
startup: application
boot: auto
webui: "http://[HOST]:[PORT:3000]"
ports:
  "3000/tcp": 3000
map: ["data:rw"]
environment:
  DATA_PATH: /data/koinsight_data
