name: Calibre-Web Automated
version: 1.0.0
slug: calibre_web_automated
description: "Home Assistant Addon for crocodilestick/calibre-web-automated"
arch: ["aarch64"]
startup: application
boot: auto
ports:
  "8083/tcp": 8084
apparmor: false
map: ["share:rw"]
privileged:
  - SYS_ADMIN
init: false
image: "ghcr.io/dimabutenko/ha-addon-cwa"
environment:
  TZ: "Europe/Warsaw"
  PUID: "1000"
  PGID: "1000"
