name: "SMBv1 Share"
url: "https://github.com/dimabutenko/home-assistant-addons"
version: "1.1.0"
slug: "samba_v1"
description: "Samba-server with SMBv1 support"
arch: ["aarch64"]
apparmor: false
map: ["media:rw"]
privileged:
  - SYS_ADMIN
init: false
ports:
  139/tcp: 139
  445/tcp: 445
options: {}
schema: {}