[global]
   workgroup = WORKGROUP
   server string = HA Hikvision Share
   server min protocol = NT1
   ntlm auth = yes
   bind interfaces only = yes
   interfaces = lo eth0 wlan0
   security = user
   map to guest = Bad User
   log file = /dev/stdout
   max log size = 50

[hikvision_share]
   path = /media/hikvision
   max disk size = 512000
   browseable = yes
   writable = yes
   guest ok = yes
   read only = no
   force user = root
   create mask = 0777
   directory mask = 0777

