name: Build & Publish Add-on

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    uses: home-assistant/addons/.github/workflows/addon.yml@master
    with:
      path: "calibre_web_automated"
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}